# Generated by Django 5.0.6 on 2024-06-15 11:39

import mini_pic_wall.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_collage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(storage=mini_pic_wall.api.models.Sha256NameStorage(), upload_to='images/'),
        ),
    ]
