# Generated by Django 5.0.6 on 2024-06-15 13:45

import django.db.models.manager
import mini_pic_wall.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_picture_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='picture',
            managers=[
                ('picture', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='thumbnail',
            field=models.ImageField(blank=True, storage=mini_pic_wall.api.models.Sha256NameStorage(), upload_to='thumbnails/'),
        ),
    ]
