# Generated by Django 5.0.6 on 2024-06-16 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_picture_managers_picture_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_image', models.ImageField(upload_to='images/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='thumbnails/')),
            ],
        ),
        migrations.AlterModelManagers(
            name='picture',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='picture',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='picture',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='api.image'),
        ),
    ]
