services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    volumes:
      - static_files:/home/app/static
      - media_files:/home/app/media
    ports:
      - 80:80
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 mini_pic_wall.wsgi
    volumes:
      - static_files:/home/app/static
      - media_files:/home/app/media
    env_file:
      - .env
    depends_on:
      - postgres
      - celery

  celery:
    build:
      context: .
      dockerfile: web.Dockerfile
    command: celery --app=mini_pic_wall worker
    volumes:
      - media_files:/home/app/media
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

  redis:
    image: redis:7-alpine


volumes:
  postgres_data:
  static_files:
  media_files:
