services:
  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 mini_pic_wall.wsgi
    volumes:
      - static_files:/home/app/static
      - media_files:/home/app/media
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    volumes:
      - static_files:/home/app/static
      - media_files:/home/app/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_files:
  media_files:
