services:
  nginx:
    build:
      dockerfile: nginx.Dockerfile
    volumes:
      - static_files:/home/app/static
      - media_files:/home/app/media
    ports:
      - 80:80

  web:
    build: mini_pic_wall
    command: python manage.py runserver 0.0.0.0:8000
    env_file: "dev.env"
    volumes:
      - ./mini_pic_wall/:/home/app/
      - static_files:/home/app/static
      - media_files:/home/app/media

  celery:
    build: mini_pic_wall
    command: celery --app=mini_pic_wall worker
    env_file: "dev.env"
    volumes:
      - ./mini_pic_wall:/home/app/
      - media_files:/home/app/media

  postgres:
    image: postgres:16-alpine
    env_file: "dev.env"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7-alpine


volumes:
  postgres_data:
  static_files:
  media_files:
