services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    volumes:
      - static_files:/home/app/static
      - media_files:/home/app/media
    ports:
      - 80:80
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: web.prod.Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 mini_pic_wall.wsgi
    env_file: "prod.env"
    volumes:
      - static_files:/home/app/static
      - media_files:/home/app/media
    depends_on:
      - postgres
      - celery

  celery:
    build:
      context: .
      dockerfile: web.prod.Dockerfile
    command: celery --app=mini_pic_wall worker
    env_file: "prod.env"
    volumes:
      - media_files:/home/app/media
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    env_file: "prod.env"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7-alpine


volumes:
  postgres_data:
  static_files:
  media_files:
